language: java

jdk:
  - openjdk7
  - oraclejdk8

notifications:
  # Email notifications are disabled to not annoy anybody.
  email: false

branches:
  only:
    - master

after_success:
  - echo -e https://raw.githubusercontent.com/abranhe/hack/master/travis/success | bash -s
